upgrade to sbt 1.9.2
for compatibility with Java 20 and 21.

This also disables inlining due to this compile error:

    java.lang.AssertionError: assertion failed: ClassBType.info not yet assigned: Ljava/lang/Object;